# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\Final-project\gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1434, 1980)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mplwindow = QtWidgets.QWidget(self.centralwidget)
        self.mplwindow.setAutoFillBackground(False)
        self.mplwindow.setObjectName("mplwindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mplwindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.mplwindow)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout.addWidget(self.mplwindow, 1, 2, 4, 4)
        self.gp_image = QtWidgets.QGroupBox(self.centralwidget)
        self.gp_image.setMinimumSize(QtCore.QSize(250, 0))
        self.gp_image.setMaximumSize(QtCore.QSize(250, 16777215))
        self.gp_image.setObjectName("gp_image")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gp_image)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gp_load = QtWidgets.QGroupBox(self.gp_image)
        self.gp_load.setObjectName("gp_load")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gp_load)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_image_load = QtWidgets.QPushButton(self.gp_load)
        self.btn_image_load.setObjectName("btn_image_load")
        self.gridLayout_2.addWidget(self.btn_image_load, 0, 0, 1, 1)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.gp_load)
        self.groupBox = QtWidgets.QGroupBox(self.gp_image)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.txt_size = QtWidgets.QLabel(self.groupBox)
        self.txt_size.setObjectName("txt_size")
        self.gridLayout_5.addWidget(self.txt_size, 0, 0, 1, 1)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.groupBox)
        self.gp_method = QtWidgets.QGroupBox(self.gp_image)
        self.gp_method.setObjectName("gp_method")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gp_method)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.com_image = QtWidgets.QComboBox(self.gp_method)
        self.com_image.setMinimumSize(QtCore.QSize(0, 30))
        self.com_image.setObjectName("com_image")
        self.com_image.addItem("")
        self.gridLayout_7.addWidget(self.com_image, 0, 0, 1, 1)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.gp_method)
        self.gp_tresh = QtWidgets.QGroupBox(self.gp_image)
        self.gp_tresh.setObjectName("gp_tresh")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gp_tresh)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ch_THRESH_TRUNC = QtWidgets.QCheckBox(self.gp_tresh)
        self.ch_THRESH_TRUNC.setObjectName("ch_THRESH_TRUNC")
        self.gridLayout_4.addWidget(self.ch_THRESH_TRUNC, 1, 0, 1, 1)
        self.btn_process_tresh = QtWidgets.QPushButton(self.gp_tresh)
        self.btn_process_tresh.setObjectName("btn_process_tresh")
        self.gridLayout_4.addWidget(self.btn_process_tresh, 6, 0, 1, 1)
        self.slider_threshold = QtWidgets.QSlider(self.gp_tresh)
        self.slider_threshold.setMaximum(255)
        self.slider_threshold.setProperty("value", 127)
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName("slider_threshold")
        self.gridLayout_4.addWidget(self.slider_threshold, 5, 0, 1, 1)
        self.tx_tresh_value = QtWidgets.QLabel(self.gp_tresh)
        self.tx_tresh_value.setObjectName("tx_tresh_value")
        self.gridLayout_4.addWidget(self.tx_tresh_value, 4, 0, 1, 1)
        self.ch_THRESH_TOZERO = QtWidgets.QCheckBox(self.gp_tresh)
        self.ch_THRESH_TOZERO.setObjectName("ch_THRESH_TOZERO")
        self.gridLayout_4.addWidget(self.ch_THRESH_TOZERO, 2, 0, 1, 1)
        self.ch_THRESH_BINARY = QtWidgets.QCheckBox(self.gp_tresh)
        self.ch_THRESH_BINARY.setObjectName("ch_THRESH_BINARY")
        self.gridLayout_4.addWidget(self.ch_THRESH_BINARY, 0, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gp_tresh)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 3, 0, 1, 1)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.gp_tresh)
        self.gp_edgedetection = QtWidgets.QGroupBox(self.gp_image)
        self.gp_edgedetection.setFlat(False)
        self.gp_edgedetection.setObjectName("gp_edgedetection")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gp_edgedetection)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_7 = QtWidgets.QFrame(self.gp_edgedetection)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_6.addWidget(self.line_7, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gp_edgedetection)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.com_edge = QtWidgets.QComboBox(self.gp_edgedetection)
        self.com_edge.setObjectName("com_edge")
        self.com_edge.addItem("")
        self.com_edge.addItem("")
        self.com_edge.addItem("")
        self.gridLayout_6.addWidget(self.com_edge, 1, 0, 1, 1)
        self.gp_canny = QtWidgets.QGroupBox(self.gp_edgedetection)
        self.gp_canny.setTitle("")
        self.gp_canny.setObjectName("gp_canny")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gp_canny)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.txt_ede_method = QtWidgets.QLabel(self.gp_canny)
        self.txt_ede_method.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_ede_method.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_ede_method.setObjectName("txt_ede_method")
        self.gridLayout_8.addWidget(self.txt_ede_method, 7, 0, 1, 1)
        self.txt_canny_tresh1 = QtWidgets.QLabel(self.gp_canny)
        self.txt_canny_tresh1.setObjectName("txt_canny_tresh1")
        self.gridLayout_8.addWidget(self.txt_canny_tresh1, 10, 0, 1, 1)
        self.slider_tresh1 = QtWidgets.QSlider(self.gp_canny)
        self.slider_tresh1.setMaximum(500)
        self.slider_tresh1.setProperty("value", 100)
        self.slider_tresh1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tresh1.setObjectName("slider_tresh1")
        self.gridLayout_8.addWidget(self.slider_tresh1, 11, 0, 1, 1)
        self.txt_outsu = QtWidgets.QLabel(self.gp_canny)
        self.txt_outsu.setObjectName("txt_outsu")
        self.gridLayout_8.addWidget(self.txt_outsu, 1, 0, 1, 1)
        self.txt_edge_binary = QtWidgets.QLabel(self.gp_canny)
        self.txt_edge_binary.setFrameShape(QtWidgets.QFrame.Box)
        self.txt_edge_binary.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_edge_binary.setObjectName("txt_edge_binary")
        self.gridLayout_8.addWidget(self.txt_edge_binary, 0, 0, 1, 1)
        self.txt_tresh_canny = QtWidgets.QLabel(self.gp_canny)
        self.txt_tresh_canny.setObjectName("txt_tresh_canny")
        self.gridLayout_8.addWidget(self.txt_tresh_canny, 4, 0, 1, 1)
        self.slider_thresh2 = QtWidgets.QSlider(self.gp_canny)
        self.slider_thresh2.setMaximum(500)
        self.slider_thresh2.setProperty("value", 200)
        self.slider_thresh2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thresh2.setObjectName("slider_thresh2")
        self.gridLayout_8.addWidget(self.slider_thresh2, 13, 0, 1, 1)
        self.slider_thresh_canny = QtWidgets.QSlider(self.gp_canny)
        self.slider_thresh_canny.setMaximum(255)
        self.slider_thresh_canny.setSingleStep(1)
        self.slider_thresh_canny.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thresh_canny.setObjectName("slider_thresh_canny")
        self.gridLayout_8.addWidget(self.slider_thresh_canny, 5, 0, 1, 1)
        self.txt_canny_tresh2 = QtWidgets.QLabel(self.gp_canny)
        self.txt_canny_tresh2.setObjectName("txt_canny_tresh2")
        self.gridLayout_8.addWidget(self.txt_canny_tresh2, 12, 0, 1, 1)
        self.btn_canny_process = QtWidgets.QPushButton(self.gp_canny)
        self.btn_canny_process.setObjectName("btn_canny_process")
        self.gridLayout_8.addWidget(self.btn_canny_process, 16, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gp_canny)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_8.addWidget(self.line_6, 6, 0, 1, 1)
        self.gridLayout_6.addWidget(self.gp_canny, 3, 0, 1, 1)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.gp_edgedetection)
        self.gp_filter = QtWidgets.QGroupBox(self.gp_image)
        self.gp_filter.setObjectName("gp_filter")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gp_filter)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.com_filter = QtWidgets.QComboBox(self.gp_filter)
        self.com_filter.setObjectName("com_filter")
        self.com_filter.addItem("")
        self.com_filter.addItem("")
        self.com_filter.addItem("")
        self.com_filter.addItem("")
        self.gridLayout_12.addWidget(self.com_filter, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gp_filter)
        self.spinBox.setMinimum(3)
        self.spinBox.setSingleStep(2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_12.addWidget(self.spinBox, 4, 0, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.gp_filter)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_12.addWidget(self.line_16, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gp_filter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gp_filter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_12.addWidget(self.label_12, 3, 0, 1, 1)
        self.btn_process_filters = QtWidgets.QPushButton(self.gp_filter)
        self.btn_process_filters.setObjectName("btn_process_filters")
        self.gridLayout_12.addWidget(self.btn_process_filters, 5, 0, 1, 1)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.gp_filter)
        self.gp_morphology = QtWidgets.QGroupBox(self.gp_image)
        self.gp_morphology.setObjectName("gp_morphology")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gp_morphology)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.txt_tresh_morph = QtWidgets.QLabel(self.gp_morphology)
        self.txt_tresh_morph.setObjectName("txt_tresh_morph")
        self.gridLayout_13.addWidget(self.txt_tresh_morph, 1, 0, 1, 1)
        self.btn_process_morphology = QtWidgets.QPushButton(self.gp_morphology)
        self.btn_process_morphology.setObjectName("btn_process_morphology")
        self.gridLayout_13.addWidget(self.btn_process_morphology, 11, 0, 1, 1)
        self.sp_morph_kernel = QtWidgets.QSpinBox(self.gp_morphology)
        self.sp_morph_kernel.setMinimum(3)
        self.sp_morph_kernel.setSingleStep(2)
        self.sp_morph_kernel.setObjectName("sp_morph_kernel")
        self.gridLayout_13.addWidget(self.sp_morph_kernel, 7, 0, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.gp_morphology)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_13.addWidget(self.line_18, 8, 0, 1, 1)
        self.sp_morph_iter = QtWidgets.QSpinBox(self.gp_morphology)
        self.sp_morph_iter.setMinimum(1)
        self.sp_morph_iter.setMaximum(10)
        self.sp_morph_iter.setObjectName("sp_morph_iter")
        self.gridLayout_13.addWidget(self.sp_morph_iter, 10, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gp_morphology)
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gp_morphology)
        self.label_15.setObjectName("label_15")
        self.gridLayout_13.addWidget(self.label_15, 9, 0, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.gp_morphology)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_13.addWidget(self.line_17, 5, 0, 1, 1)
        self.slider_thresh_morph = QtWidgets.QSlider(self.gp_morphology)
        self.slider_thresh_morph.setMaximum(256)
        self.slider_thresh_morph.setOrientation(QtCore.Qt.Horizontal)
        self.slider_thresh_morph.setObjectName("slider_thresh_morph")
        self.gridLayout_13.addWidget(self.slider_thresh_morph, 2, 0, 1, 1)
        self.txt_otsu_morph = QtWidgets.QLabel(self.gp_morphology)
        self.txt_otsu_morph.setObjectName("txt_otsu_morph")
        self.gridLayout_13.addWidget(self.txt_otsu_morph, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gp_morphology)
        self.label_13.setObjectName("label_13")
        self.gridLayout_13.addWidget(self.label_13, 3, 0, 1, 1)
        self.com_morphology = QtWidgets.QComboBox(self.gp_morphology)
        self.com_morphology.setObjectName("com_morphology")
        self.com_morphology.addItem("")
        self.gridLayout_13.addWidget(self.com_morphology, 4, 0, 1, 1)
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.gp_morphology)
        self.gp_compare_image = QtWidgets.QGroupBox(self.gp_image)
        self.gp_compare_image.setObjectName("gp_compare_image")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gp_compare_image)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gp_compare_manual = QtWidgets.QGroupBox(self.gp_compare_image)
        self.gp_compare_manual.setObjectName("gp_compare_manual")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gp_compare_manual)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.line_19 = QtWidgets.QFrame(self.gp_compare_manual)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout_15.addWidget(self.line_19, 3, 0, 1, 1)
        self.txt_otsu_compare = QtWidgets.QLabel(self.gp_compare_manual)
        self.txt_otsu_compare.setObjectName("txt_otsu_compare")
        self.gridLayout_15.addWidget(self.txt_otsu_compare, 4, 0, 1, 1)
        self.rd_health_compare = QtWidgets.QRadioButton(self.gp_compare_manual)
        self.rd_health_compare.setObjectName("rd_health_compare")
        self.gridLayout_15.addWidget(self.rd_health_compare, 1, 0, 1, 1)
        self.txt_tresh_compare = QtWidgets.QLabel(self.gp_compare_manual)
        self.txt_tresh_compare.setObjectName("txt_tresh_compare")
        self.gridLayout_15.addWidget(self.txt_tresh_compare, 5, 0, 1, 1)
        self.slider_tresh_compare = QtWidgets.QSlider(self.gp_compare_manual)
        self.slider_tresh_compare.setMaximum(256)
        self.slider_tresh_compare.setOrientation(QtCore.Qt.Horizontal)
        self.slider_tresh_compare.setObjectName("slider_tresh_compare")
        self.gridLayout_15.addWidget(self.slider_tresh_compare, 6, 0, 1, 1)
        self.sp_kernel_compare = QtWidgets.QSpinBox(self.gp_compare_manual)
        self.sp_kernel_compare.setMinimum(3)
        self.sp_kernel_compare.setSingleStep(2)
        self.sp_kernel_compare.setObjectName("sp_kernel_compare")
        self.gridLayout_15.addWidget(self.sp_kernel_compare, 8, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gp_compare_manual)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 7, 0, 1, 1)
        self.btn_process_compare_image = QtWidgets.QPushButton(self.gp_compare_manual)
        self.btn_process_compare_image.setObjectName("btn_process_compare_image")
        self.gridLayout_15.addWidget(self.btn_process_compare_image, 9, 0, 1, 1)
        self.rd_covid_compare = QtWidgets.QRadioButton(self.gp_compare_manual)
        self.rd_covid_compare.setChecked(True)
        self.rd_covid_compare.setObjectName("rd_covid_compare")
        self.gridLayout_15.addWidget(self.rd_covid_compare, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.gp_compare_manual, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gp_compare_image)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_14.addWidget(self.label_17, 13, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.gp_compare_image)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout_14.addWidget(self.line_20, 12, 0, 1, 1)
        self.com_compare_type = QtWidgets.QComboBox(self.gp_compare_image)
        self.com_compare_type.setObjectName("com_compare_type")
        self.com_compare_type.addItem("")
        self.com_compare_type.addItem("")
        self.gridLayout_14.addWidget(self.com_compare_type, 1, 0, 1, 1)
        self.txt_covid_compare = QtWidgets.QLabel(self.gp_compare_image)
        self.txt_covid_compare.setText("")
        self.txt_covid_compare.setObjectName("txt_covid_compare")
        self.gridLayout_14.addWidget(self.txt_covid_compare, 17, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gp_compare_image)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 0, 0, 1, 1)
        self.txt_normal_compare = QtWidgets.QLabel(self.gp_compare_image)
        self.txt_normal_compare.setText("")
        self.txt_normal_compare.setObjectName("txt_normal_compare")
        self.gridLayout_14.addWidget(self.txt_normal_compare, 15, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gp_compare_image)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_14.addWidget(self.label_16, 14, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gp_compare_image)
        self.label_19.setObjectName("label_19")
        self.gridLayout_14.addWidget(self.label_19, 16, 0, 1, 1)
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.gp_compare_image)
        self.gridLayout.addWidget(self.gp_image, 0, 6, 5, 1)
        self.gp_signal = QtWidgets.QGroupBox(self.centralwidget)
        self.gp_signal.setMinimumSize(QtCore.QSize(300, 0))
        self.gp_signal.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gp_signal.setObjectName("gp_signal")
        self.formLayout = QtWidgets.QFormLayout(self.gp_signal)
        self.formLayout.setObjectName("formLayout")
        self.gp_param = QtWidgets.QGroupBox(self.gp_signal)
        self.gp_param.setObjectName("gp_param")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gp_param)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ch_marker = QtWidgets.QCheckBox(self.gp_param)
        self.ch_marker.setObjectName("ch_marker")
        self.gridLayout_3.addWidget(self.ch_marker, 27, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.gp_param)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout_3.addWidget(self.line_21, 24, 0, 1, 1)
        self.binSlider = QtWidgets.QSlider(self.gp_param)
        self.binSlider.setMinimum(10)
        self.binSlider.setMaximum(500)
        self.binSlider.setOrientation(QtCore.Qt.Horizontal)
        self.binSlider.setObjectName("binSlider")
        self.gridLayout_3.addWidget(self.binSlider, 22, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gp_param)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 15, 0, 1, 1)
        self.tx_download = QtWidgets.QLabel(self.gp_param)
        self.tx_download.setObjectName("tx_download")
        self.gridLayout_3.addWidget(self.tx_download, 3, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gp_param)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 12, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gp_param)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 4, 0, 1, 1)
        self.btn_process = QtWidgets.QPushButton(self.gp_param)
        self.btn_process.setObjectName("btn_process")
        self.gridLayout_3.addWidget(self.btn_process, 31, 0, 1, 1)
        self.date_from = QtWidgets.QDateEdit(self.gp_param)
        self.date_from.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_from.setObjectName("date_from")
        self.gridLayout_3.addWidget(self.date_from, 14, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gp_param)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 7, 0, 1, 1)
        self.btn_load = QtWidgets.QPushButton(self.gp_param)
        self.btn_load.setObjectName("btn_load")
        self.gridLayout_3.addWidget(self.btn_load, 0, 0, 1, 1)
        self.txt_slider_value = QtWidgets.QLabel(self.gp_param)
        self.txt_slider_value.setObjectName("txt_slider_value")
        self.gridLayout_3.addWidget(self.txt_slider_value, 23, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gp_param)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 9, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gp_param)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 29, 0, 1, 1)
        self.date_to = QtWidgets.QDateEdit(self.gp_param)
        self.date_to.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 30), QtCore.QTime(0, 0, 0)))
        self.date_to.setObjectName("date_to")
        self.gridLayout_3.addWidget(self.date_to, 16, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gp_param)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 10, 0, 1, 1)
        self.btn_download_online = QtWidgets.QPushButton(self.gp_param)
        self.btn_download_online.setObjectName("btn_download_online")
        self.gridLayout_3.addWidget(self.btn_download_online, 1, 0, 1, 1)
        self.com_method = QtWidgets.QComboBox(self.gp_param)
        self.com_method.setMinimumSize(QtCore.QSize(0, 25))
        self.com_method.setObjectName("com_method")
        self.com_method.addItem("")
        self.gridLayout_3.addWidget(self.com_method, 11, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gp_param)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 19, 0, 1, 1)
        self.ch_temp = QtWidgets.QCheckBox(self.gp_param)
        self.ch_temp.setObjectName("ch_temp")
        self.gridLayout_3.addWidget(self.ch_temp, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gp_param)
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 21, 0, 1, 1)
        self.pb_download = QtWidgets.QProgressBar(self.gp_param)
        self.pb_download.setProperty("value", 0)
        self.pb_download.setObjectName("pb_download")
        self.gridLayout_3.addWidget(self.pb_download, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gp_param)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 13, 0, 1, 1)
        self.com_shift = QtWidgets.QComboBox(self.gp_param)
        self.com_shift.setMinimumSize(QtCore.QSize(0, 25))
        self.com_shift.setObjectName("com_shift")
        self.com_shift.addItem("")
        self.com_shift.addItem("")
        self.com_shift.addItem("")
        self.com_shift.addItem("")
        self.com_shift.addItem("")
        self.gridLayout_3.addWidget(self.com_shift, 25, 0, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.gp_param)
        self.groupBox_3 = QtWidgets.QGroupBox(self.gp_signal)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.txt_mean_new_case = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_mean_new_case.setFont(font)
        self.txt_mean_new_case.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_mean_new_case.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_mean_new_case.setObjectName("txt_mean_new_case")
        self.gridLayout_9.addWidget(self.txt_mean_new_case, 5, 0, 1, 1)
        self.txt_co = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_co.setFont(font)
        self.txt_co.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_co.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_co.setTextFormat(QtCore.Qt.AutoText)
        self.txt_co.setWordWrap(False)
        self.txt_co.setObjectName("txt_co")
        self.gridLayout_9.addWidget(self.txt_co, 6, 0, 1, 1)
        self.txt_std_new_case = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_std_new_case.setFont(font)
        self.txt_std_new_case.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_std_new_case.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_std_new_case.setObjectName("txt_std_new_case")
        self.gridLayout_9.addWidget(self.txt_std_new_case, 4, 0, 1, 1)
        self.txt_population = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_population.setFont(font)
        self.txt_population.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_population.setFrameShadow(QtWidgets.QFrame.Plain)
        self.txt_population.setObjectName("txt_population")
        self.gridLayout_9.addWidget(self.txt_population, 0, 0, 1, 1)
        self.txt_max_case = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_max_case.setFont(font)
        self.txt_max_case.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_max_case.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_max_case.setObjectName("txt_max_case")
        self.gridLayout_9.addWidget(self.txt_max_case, 1, 0, 1, 1)
        self.txt_date_max = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_date_max.setFont(font)
        self.txt_date_max.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_date_max.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_date_max.setObjectName("txt_date_max")
        self.gridLayout_9.addWidget(self.txt_date_max, 2, 0, 1, 1)
        self.txt_variance_new_cases = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_variance_new_cases.setFont(font)
        self.txt_variance_new_cases.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_variance_new_cases.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_variance_new_cases.setObjectName("txt_variance_new_cases")
        self.gridLayout_9.addWidget(self.txt_variance_new_cases, 3, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_co_00 = QtWidgets.QLabel(self.groupBox_5)
        self.txt_co_00.setText("")
        self.txt_co_00.setObjectName("txt_co_00")
        self.horizontalLayout_2.addWidget(self.txt_co_00)
        self.line_9 = QtWidgets.QFrame(self.groupBox_5)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_2.addWidget(self.line_9)
        self.txt_co_01 = QtWidgets.QLabel(self.groupBox_5)
        self.txt_co_01.setText("")
        self.txt_co_01.setObjectName("txt_co_01")
        self.horizontalLayout_2.addWidget(self.txt_co_01)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_10 = QtWidgets.QFrame(self.groupBox_5)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_2.addWidget(self.line_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txt_co_10 = QtWidgets.QLabel(self.groupBox_5)
        self.txt_co_10.setText("")
        self.txt_co_10.setObjectName("txt_co_10")
        self.horizontalLayout_3.addWidget(self.txt_co_10)
        self.line_11 = QtWidgets.QFrame(self.groupBox_5)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_3.addWidget(self.line_11)
        self.txt_co_11 = QtWidgets.QLabel(self.groupBox_5)
        self.txt_co_11.setText("")
        self.txt_co_11.setObjectName("txt_co_11")
        self.horizontalLayout_3.addWidget(self.txt_co_11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout_10.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_5, 8, 0, 1, 1)
        self.txt_covariance = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_covariance.setFont(font)
        self.txt_covariance.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.txt_covariance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.txt_covariance.setObjectName("txt_covariance")
        self.gridLayout_9.addWidget(self.txt_covariance, 7, 0, 1, 1)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.groupBox_3)
        self.gp_compare = QtWidgets.QGroupBox(self.gp_signal)
        self.gp_compare.setMinimumSize(QtCore.QSize(0, 0))
        self.gp_compare.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gp_compare.setObjectName("gp_compare")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gp_compare)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.line_14 = QtWidgets.QFrame(self.gp_compare)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_11.addWidget(self.line_14, 9, 0, 1, 1)
        self.date_to_compare = QtWidgets.QDateEdit(self.gp_compare)
        self.date_to_compare.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 30), QtCore.QTime(0, 0, 0)))
        self.date_to_compare.setObjectName("date_to_compare")
        self.gridLayout_11.addWidget(self.date_to_compare, 13, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gp_compare)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 4, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gp_compare)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_11.addWidget(self.line_12, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gp_compare)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 2, 0, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.gp_compare)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_11.addWidget(self.line_15, 14, 0, 1, 1)
        self.com_method_compare = QtWidgets.QComboBox(self.gp_compare)
        self.com_method_compare.setMinimumSize(QtCore.QSize(0, 25))
        self.com_method_compare.setObjectName("com_method_compare")
        self.com_method_compare.addItem("")
        self.gridLayout_11.addWidget(self.com_method_compare, 8, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.gp_compare)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_11.addWidget(self.line_13, 6, 0, 1, 1)
        self.date_from_compare = QtWidgets.QDateEdit(self.gp_compare)
        self.date_from_compare.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_from_compare.setObjectName("date_from_compare")
        self.gridLayout_11.addWidget(self.date_from_compare, 11, 0, 1, 1)
        self.com_second_country = QtWidgets.QComboBox(self.gp_compare)
        self.com_second_country.setMinimumSize(QtCore.QSize(0, 25))
        self.com_second_country.setObjectName("com_second_country")
        self.com_second_country.addItem("")
        self.gridLayout_11.addWidget(self.com_second_country, 5, 0, 1, 1)
        self.btn_load_Compare = QtWidgets.QPushButton(self.gp_compare)
        self.btn_load_Compare.setObjectName("btn_load_Compare")
        self.gridLayout_11.addWidget(self.btn_load_Compare, 0, 0, 1, 1)
        self.btn_process_compare = QtWidgets.QPushButton(self.gp_compare)
        self.btn_process_compare.setObjectName("btn_process_compare")
        self.gridLayout_11.addWidget(self.btn_process_compare, 15, 0, 1, 1)
        self.comboBox_compare = QtWidgets.QComboBox(self.gp_compare)
        self.comboBox_compare.setMinimumSize(QtCore.QSize(0, 25))
        self.comboBox_compare.setObjectName("comboBox_compare")
        self.comboBox_compare.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_compare, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gp_compare)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gp_compare)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 10, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gp_compare)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 12, 0, 1, 1)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.gp_compare)
        self.gridLayout.addWidget(self.gp_signal, 0, 0, 5, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 5, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setContentsMargins(9, 0, -1, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_compare_country = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_compare_country.setMinimumSize(QtCore.QSize(0, 35))
        self.btn_compare_country.setObjectName("btn_compare_country")
        self.horizontalLayout.addWidget(self.btn_compare_country)
        self.btnSignal = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSignal.setMinimumSize(QtCore.QSize(0, 35))
        self.btnSignal.setObjectName("btnSignal")
        self.horizontalLayout.addWidget(self.btnSignal)
        self.btnImage = QtWidgets.QPushButton(self.groupBox_2)
        self.btnImage.setMinimumSize(QtCore.QSize(0, 35))
        self.btnImage.setObjectName("btnImage")
        self.horizontalLayout.addWidget(self.btnImage)
        self.gridLayout.addWidget(self.groupBox_2, 0, 3, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1434, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gp_image.setTitle(_translate("MainWindow", "Image"))
        self.gp_load.setTitle(_translate("MainWindow", "Load"))
        self.btn_image_load.setText(_translate("MainWindow", "Load Image"))
        self.groupBox.setTitle(_translate("MainWindow", "Info"))
        self.txt_size.setText(_translate("MainWindow", "Size covid image:"))
        self.gp_method.setTitle(_translate("MainWindow", "Analysis Methods"))
        self.com_image.setItemText(0, _translate("MainWindow", "Select Method"))
        self.gp_tresh.setTitle(_translate("MainWindow", "Threshold"))
        self.ch_THRESH_TRUNC.setText(_translate("MainWindow", "THRESH_TRUNC"))
        self.btn_process_tresh.setText(_translate("MainWindow", "Process"))
        self.tx_tresh_value.setText(_translate("MainWindow", "Threshold value: 127"))
        self.ch_THRESH_TOZERO.setText(_translate("MainWindow", "THRESH_TOZERO"))
        self.ch_THRESH_BINARY.setText(_translate("MainWindow", "THRESH_BINARY"))
        self.gp_edgedetection.setTitle(_translate("MainWindow", "Edge Detection"))
        self.label_4.setText(_translate("MainWindow", "Method Selection"))
        self.com_edge.setItemText(0, _translate("MainWindow", "Canny"))
        self.com_edge.setItemText(1, _translate("MainWindow", "Prewitt"))
        self.com_edge.setItemText(2, _translate("MainWindow", "Sobel"))
        self.txt_ede_method.setText(_translate("MainWindow", "Canny for original image"))
        self.txt_canny_tresh1.setText(_translate("MainWindow", "Thereshold Value one:"))
        self.txt_outsu.setText(_translate("MainWindow", "Otsu Threshold value:"))
        self.txt_edge_binary.setText(_translate("MainWindow", "Canny For Binary image"))
        self.txt_tresh_canny.setText(_translate("MainWindow", "Threshold value: "))
        self.txt_canny_tresh2.setText(_translate("MainWindow", "Thereshold Value two:"))
        self.btn_canny_process.setText(_translate("MainWindow", "Process"))
        self.gp_filter.setTitle(_translate("MainWindow", "Filters"))
        self.com_filter.setItemText(0, _translate("MainWindow", "Median"))
        self.com_filter.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.com_filter.setItemText(2, _translate("MainWindow", "Averaging"))
        self.com_filter.setItemText(3, _translate("MainWindow", "Laplacian"))
        self.label_11.setText(_translate("MainWindow", "Select Method"))
        self.label_12.setText(_translate("MainWindow", "Kernel size"))
        self.btn_process_filters.setText(_translate("MainWindow", "Process"))
        self.gp_morphology.setTitle(_translate("MainWindow", "Morphology"))
        self.txt_tresh_morph.setText(_translate("MainWindow", "Threshold Value:"))
        self.btn_process_morphology.setText(_translate("MainWindow", "Process"))
        self.label_14.setText(_translate("MainWindow", "Kernel Size"))
        self.label_15.setText(_translate("MainWindow", "Number of itteration"))
        self.txt_otsu_morph.setText(_translate("MainWindow", "Otsu Value:"))
        self.label_13.setText(_translate("MainWindow", "Select Method"))
        self.com_morphology.setItemText(0, _translate("MainWindow", "Erosion"))
        self.gp_compare_image.setTitle(_translate("MainWindow", "Compare"))
        self.gp_compare_manual.setTitle(_translate("MainWindow", "Manual"))
        self.txt_otsu_compare.setText(_translate("MainWindow", "Otsu value:"))
        self.rd_health_compare.setText(_translate("MainWindow", "Health Person CT-scan"))
        self.txt_tresh_compare.setText(_translate("MainWindow", "Threshold Value:"))
        self.label_18.setText(_translate("MainWindow", "Kernel size"))
        self.btn_process_compare_image.setText(_translate("MainWindow", "Process"))
        self.rd_covid_compare.setText(_translate("MainWindow", "Covid Patient  CT-scan"))
        self.label_17.setText(_translate("MainWindow", "Comparision"))
        self.com_compare_type.setItemText(0, _translate("MainWindow", "Automatic"))
        self.com_compare_type.setItemText(1, _translate("MainWindow", "Manual"))
        self.label_20.setText(_translate("MainWindow", "Choose Automatic or Manual"))
        self.label_16.setText(_translate("MainWindow", "Percentage of white Pixel in normal:"))
        self.label_19.setText(_translate("MainWindow", "Percentage of white Pixel Covid case:"))
        self.gp_signal.setTitle(_translate("MainWindow", "Signal"))
        self.gp_param.setTitle(_translate("MainWindow", "Covid-19 Data for a country"))
        self.ch_marker.setText(_translate("MainWindow", "Set Marker and get data by click"))
        self.label_2.setText(_translate("MainWindow", "Time To:"))
        self.tx_download.setText(_translate("MainWindow", "TextLabel"))
        self.btn_process.setText(_translate("MainWindow", "Process"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Selsect The Country"))
        self.btn_load.setText(_translate("MainWindow", "Load Data"))
        self.txt_slider_value.setText(_translate("MainWindow", "Bin Number: 10"))
        self.label_9.setText(_translate("MainWindow", "Data type:"))
        self.btn_download_online.setText(_translate("MainWindow", "Download Data From Website"))
        self.com_method.setItemText(0, _translate("MainWindow", "Select data type"))
        self.ch_temp.setText(_translate("MainWindow", "Temp relation with Covid-19"))
        self.label_3.setText(_translate("MainWindow", "Number of bins for histogram"))
        self.label.setText(_translate("MainWindow", "Time from"))
        self.com_shift.setItemText(0, _translate("MainWindow", "Shifted date of new deaths"))
        self.com_shift.setItemText(1, _translate("MainWindow", "One week"))
        self.com_shift.setItemText(2, _translate("MainWindow", "Two week"))
        self.com_shift.setItemText(3, _translate("MainWindow", "Three week"))
        self.com_shift.setItemText(4, _translate("MainWindow", "One month"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Calculations and Info"))
        self.txt_mean_new_case.setText(_translate("MainWindow", "Mean:"))
        self.txt_co.setText(_translate("MainWindow", "Correlation coefficient:"))
        self.txt_std_new_case.setText(_translate("MainWindow", "Standard deviation:"))
        self.txt_population.setText(_translate("MainWindow", "population: "))
        self.txt_max_case.setText(_translate("MainWindow", "Max number of cases: "))
        self.txt_date_max.setText(_translate("MainWindow", "Date of max new case:"))
        self.txt_variance_new_cases.setText(_translate("MainWindow", "Variance:"))
        self.txt_covariance.setText(_translate("MainWindow", "Covariance Matrix:"))
        self.gp_compare.setTitle(_translate("MainWindow", "Covid-19 data comprasion "))
        self.label_6.setText(_translate("MainWindow", "Select Second Country"))
        self.label_5.setText(_translate("MainWindow", "Select First Country"))
        self.com_method_compare.setItemText(0, _translate("MainWindow", "Select Datat Type"))
        self.com_second_country.setItemText(0, _translate("MainWindow", "Selcect Second Country"))
        self.btn_load_Compare.setText(_translate("MainWindow", "Load Data"))
        self.btn_process_compare.setText(_translate("MainWindow", "Process"))
        self.comboBox_compare.setItemText(0, _translate("MainWindow", "Select First Country"))
        self.label_7.setText(_translate("MainWindow", "Select Datat Type"))
        self.label_8.setText(_translate("MainWindow", "Date From"))
        self.label_10.setText(_translate("MainWindow", "Date to"))
        self.btn_compare_country.setText(_translate("MainWindow", "Covid-19 data comparison "))
        self.btnSignal.setText(_translate("MainWindow", "Covid-19 Data for a country"))
        self.btnImage.setText(_translate("MainWindow", "        Image Processing      "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
